### PR TITLE
Change the style of the website based on the browsers theme

### PR DESCRIPTION
**Pull request by wjtje**
Currently the site uses have dark mode and have light mode,
this PR fixes part of it by changing a lot of ui elements to the correct theme.

### Dark mode

image

### Light mode

image

### CODE REVIEW

**Comment by jbelien** [comment]
Looks (really) good so far ! 👍 

- I would remove `navbar-dark` from the `index.html` files and move what's needed to SCSS (to avoid any confusion)
- I would add a switch so people can change the theme
- I would also apply light/dark theme to the baselayer (switch between [`light-v10`](https://www.mapbox.com/maps/light) and [`dark-v10`](https://www.mapbox.com/maps/dark)) unless the user specified the style to use with `app.style` (see [Belgrade](https://github.com/EqualStreetNames/equalstreetnames-belgrade/blob/master/html/sr/index.html#L224))

Those changes will have an impact on the HTML files for each city, this is not an issue (see https://github.com/EqualStreetNames/equalstreetnames/issues/202#issuecomment-849353164).

Let me know if you need help woth the JavaScript part.

**Comment by jbelien** [comment]
You don't need to recreate the whole map, you can just change the style (see https://docs.mapbox.com/mapbox-gl-js/example/setstyle/)

**Comment by wjtje** [comment]
Yes that is a options but then all the custom data doesn't show up.

### Using map.setStyle

image

### Using the current 'solution'

image

**Comment by wjtje** [comment]
I have added a theme dropdown in the template (https://github.com/wjtje/equalstreetnames-template/commit/279c16d5b477573081eb124409b4ebeae400298e) that will override the system setting.

**Comment by jbelien** [comment]
> I have added a theme dropdown in the template (wjtje/equalstreetnames-template@279c16d) that will override the system setting.

That works but to be honest I would prefer just a switch (light/dark) with the system as default.

**Comment by wjtje** [comment]
I have replaced the dropdown menu with a toggle switch.

image

image

**Comment by jbelien** [comment]
This is starting to look REALLY nice !

Text "Light/dark mode" is a bit too long.
I would replace it by an icon (like [`fa-adjust`](https://fontawesome.com/v5.15/icons/adjust?style=solid) for instance).

Your screenshots also made me realize we will need to change the default color of the ways/relations in light mode.

**Comment by wjtje** [comment]
Maybe it's an idea to create two sperate colour pallets, one for light mode and one for dark mode. Because there is a readability issue with some colours in the chart with the darker background.

image

**Comment by jbelien** [comment]
Sounds like a good idea ... but the color selection always have been tricky.
It should also still be easily customizable (like they did for [Berlin](https://equalstreetnames-berlin.openstreetmap.de/)).

**Comment by eginhard** [comment]
> Maybe it's an idea to create two sperate colour pallets, one for light mode and one for dark mode. Because there is a readability issue with some colours in the chart with the darker background.
> 
> image

Yes, the purple streets are also very hard to spot on the dark map, even more so because there are only so few of them. I quite like Berlin's colours.

**Comment by jbelien** [comment]
I find the "male (cis) yellow" and "blue intersex" a bit hard to read on a white background in Berlin's color selection.

But maybe we can try current color selection (with darker default color for the ways/relations) for light mode and Berlin's color selection for dark mode. Worth the try ! 😄

**Comment by wjtje** [comment]
### Light mode with a darker default color

image

### Full dark mode with the colors from Berin

image

**Comment by jbelien** [comment]
I do like it ! 🤩 

Buuut ... in dark mode, I would switch "male (cis)" and "female (cis)" color so we keep the yellow-ish color for "male (cis)" and it's stay consistent when we switch.
I would also keep the same color for "male (trans)" and "female (trans)" like we do currently.

**Comment by wjtje** [comment]
Changed it

image

**Comment by wjtje** [comment]
I have added the separate color pallets but I don't know a good way to switch between them.

You can use this to figure out if the site is in dark mode or not:
```ts
(document.getElementById('themeSwitch') as HTMLInputElement).checked
```

**Comment by jbelien** [comment]
No worries, I'll have a look this weekend :)

**Comment by jbelien** [comment]
@wjtje I've refactored a few things to apply the theme switch to the map and chart.

**Comment by wjtje** [comment]
Looks good!

I have create a pull request on the template with the theme switch (https://github.com/EqualStreetNames/equalstreetnames-template/pull/4)

**Review by RobinLinde — APPROVED** [review]
Looks very nice!

I've now also changed [equalstreetnames.eu](https://equalstreetnames.eu/) to look a bit more similar.

**Comment by jbelien** [comment]
Not a big fan of the last 2 updates (bbc728304bdbc3d8350c7adea951af55b8002dd2 & 311ae275bbc908d520644c54aff4a3ed022257f1) to be honest.

What was the issue with `typeof` ?
I really dislike the `if (variable)` check, it's too loose.

For the icons, it seems strange to mix use of FontAwesome CSS font with "hardcoded" SVG ; it makes it confusing if we want to update the icon.
Why is the icon not showing on mobile ?

**Comment by wjtje** [comment]
The icon wasn't showing on mobile because there isn't a `navbar-dark` or `navbar-light` class on the navbar. (I will change the icon to use FontAwesome CSS)

The `typeof` check wasn't working:
image
Screenshot from @RobinLinde

`console.log(typeof themeSwitch)` if the switch doesn't exsist:
image


`console.log(typeof themeSwitch)` if the switch exsist:
image

Then your typeof check (`typeof themeSwitch !== 'undefined'`) would always return True, I will change to check to `typeof themeSwitch?.checked !== 'undefined'` because that works.

**Comment by jbelien** [comment]
> The icon wasn't showing on mobile because there isn't a navbar-dark or navbar-light class on the navbar. (I will change the icon to use FontAwesome CSS)

👍 
(sorry, I didn't understand you were referring to the "burger icon" from Bootstrap)

> Then your typeof check (typeof themeSwitch !== 'undefined') would always return True, I will change to check to typeof themeSwitch?.checked !== 'undefined' because that works.

Also seems strange. 😄 
But no worries, I'll need to dive into it a bit more. I'll check that this weekend.

**Comment by jbelien** [comment]
@wjtje You're right.

Check should have been `themeSwitch !== null` instead of `typeof themeSwitch !== 'undefined'` in my [previous commit](https://github.com/EqualStreetNames/equalstreetnames/pull/203/commits/27789ee6685d3db391e229b1eda393e83203b949).
But `typeof themeSwitch?.checked !== 'undefined'` works just as fine! 👍

**Comment by jbelien** [comment]
I've update the dark color palette:

- Add missing color for non-binary
- Use same color for transgender, intersex, and non-binary to stay consistent with light color palette
- Change color for unknown ; it was too close to the color used by transgender, intersex, and non-binary

**Comment by jbelien** [comment]
@wjtje If you think this is production ready, here is my "battle plan" for next week : #231 🚀

**Comment by wjtje** [comment]
It's probably best to update bootstrap to version 5 before adding these changes. (In case something brakes)

**Comment by jbelien** [comment]
Thanks a lot for your great work @wjtje ! 👍

**Pull request merged**
