### PR TITLE
add Braine-l'Alleud to list of Cities

### PR DESCRIPTION
**Pull request by eMerzh**
Add Braine-l'Alleud to the cities.
(+ auto format the table using prettier)

### CODE REVIEW

**Review by jbelien — CHANGES_REQUESTED** [review]
Please keep Brussels first in the cities list since it's where the project was initiated (that's why Brusssels is before Brugge in the list 😄)

**Comment by eMerzh** [comment]
oh right... thought i'd sort it , but yeah right 👍

**Comment by jbelien** [comment]
> oh right... thought i'd sort it , but yeah right 👍

Haha, yes, it's sorted ; I just kept Brussels first.
Braine-l'Alleud can go between Brussels and Brugge in the list. 😃

**Review by jbelien — APPROVED** [review]

**Comment by jbelien** [comment]
Thanks! 👍

**Pull request merged**
