### PR TITLE
Add Cape Town, South Africa

### LINKED ISSUE #635: Wish to start EqualStreetNames.CapeTown
Available here: https://github.com/Rodeobe/CapeTownEqualStreetNames

How can I get this transfered to you, the "EqualStreetNames organization"? Thx

### PR DESCRIPTION
**Pull request by jbelien**
- [x] Add submodule
- [x] Update README.md
- [x] Update `cities.json` in https://github.com/EqualStreetNames/module-global/commit/1208f1332eb6f1324a06facd175579e498619dc3
- [x] Update `package.json` in https://github.com/EqualStreetNames/module-website/commit/845628de9aa6620de1a90bca76e290e6bc2164af
- [x] Create automated update in https://github.com/EqualStreetNames/equalstreetnames-capetown/commit/207ab7a1bd8442addda835a57d7fd5130afffca4
- [x] Add `MAPBOX_TOKEN` secret
- [x] Create automated deployment in https://github.com/EqualStreetNames/equalstreetnames-capetown/commit/19888a825f2c5f9cea7940f7d8377e477e9e1e5b

Close #635

### CODE REVIEW

**Comment by Rodeobe** [comment]
Adding the Mapbox token as a "Action Secret": done

**Comment by jbelien** [comment]
> Adding the Mapbox token as a "Action Secret": done

Thanks!
But unfortunately the token should be named `MAPBOX_TOKEN` and not `MAPBOX_ACCESS_TOKEN`.
Since we can't rename a secret, could you remove the `MAPBOX_ACCESS_TOKEN` and create a `MAPBOX_TOKEN` with the correct token value ?

**Comment by Rodeobe** [comment]
Hey, I correct the secret.

Op wo 26 okt. 2022 om 20:30 schreef Jonathan Beliën <
***@***.***>:

**Comment by jbelien** [comment]
🚀 Deployed: https://cape-town.equalstreetnames.org/

**Pull request merged**
