### PR TITLE
Create process metadata

### LINKED ISSUE #186: Add "last updated"
As in the subject, would be helpful for street name maintainers having this information in the info box.

### PR DESCRIPTION
**Pull request by jbelien**
- Regroup `sources.json` and `statistics.json` in `metadata.json`
- Add `lastUpdate` (close #186)
- Update global build script
- Update website build script (need update of HTML templates to display datetime of last update)
- Update documentation

---

image

### CODE REVIEW

**Comment by RobinLinde** [comment]
Will update [statistics.equalstreetnames.eu](https://statistics.equalstreetnames.eu/) soon, seems like it shouldn't be too hard to do.

**Comment by RobinLinde** [comment]
That didn't take too long: https://github.com/RobinLinde/statistics/commit/025f1a0aecdbdca68ab8602754efe64e8077f51d

**Comment by jbelien** [comment]
> That didn't take too long: [RobinLinde/statistics@025f1a0](https://github.com/RobinLinde/statistics/commit/025f1a0aecdbdca68ab8602754efe64e8077f51d)

I see that you're still using `statistics.json` and `sources.json`.
Both will be deleted for all the cities after the next update, all the information are now available in `metadata.json`.

**Comment by RobinLinde** [comment]
> I see that you're still using `statistics.json` and `sources.json`.

As of now it completely rebuilds the data from the git commit history, and I'm still including them for older statistics. Currently it combines both `statistics.json` + `sources.json` and `metadata.json`, but should also work if only `metadata.json` exists.

**Pull request merged**
